[tool.poetry]
name = "orbitalpy"
version = "0.1.0"
description = ""
authors = ["Derek <derekzongnanchen@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
sgp4 = "^2.24"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
